-- Carga inicial dos itens da planilha Excel.
-- Execute UMA vez no Supabase SQL Editor.
-- Não apaga os dados existentes; se o item já existir, apenas mantém sua quantidade.

INSERT INTO public.triagem_irmaos (grupo, nome, ordem, quantidade)
VALUES
  ("ministerio", "ANCIÕES", 1, 0),
  ("ministerio", "DIÁCONOS", 2, 0),
  ("ministerio", "COOPERADORES", 3, 0),
  ("ministerio", "COOP. JOVENS E MENORES", 4, 0),
  ("ministerio", "ENC. REGIONAIS", 5, 0),
  ("ministerio", "ENC. LOCAIS", 6, 0),
  ("ministerio", "INSTRUTORES", 7, 0),
  ("ministerio", "CANDIDATOS", 8, 0),
  ("ministerio", "IRMÃOS", 9, 0),
  ("ministerio", "EXAMINADORAS", 10, 0),
  ("ministerio", "INSTRUTORAS", 11, 0),
  ("ministerio", "ORGANISTAS", 12, 0),
  ("ministerio", "ORGANISTAS DE RJM", 13, 0),
  ("ministerio", "CANDIDATAS", 14, 0),
  ("ministerio", "IRMÃS", 15, 0),
  ("musicos", "VIOLINO", 1, 0),
  ("musicos", "VIOLAS", 2, 0),
  ("musicos", "VIOLONCELOS", 3, 0),
  ("musicos", "FLAUTAS", 4, 0),
  ("musicos", "CLARINETES", 5, 0),
  ("musicos", "CLARONES", 6, 0),
  ("musicos", "OBOÉ/CORNE INGLÊS", 7, 0),
  ("musicos", "FAGOTES", 8, 0),
  ("musicos", "SAX SOPRANINO", 9, 0),
  ("musicos", "SAX SOPRANO", 10, 0),
  ("musicos", "SAX ALTO", 11, 0),
  ("musicos", "SAX TENOR", 12, 0),
  ("musicos", "SAX BARÍTONO", 13, 0),
  ("musicos", "TROMPETES", 14, 0),
  ("musicos", "POCKET", 15, 0),
  ("musicos", "FLUGELHORN", 16, 0),
  ("musicos", "TROMPA", 17, 0),
  ("musicos", "TROMBONES", 18, 0),
  ("musicos", "TROMBONITOS", 19, 0),
  ("musicos", "BOMBARDINO", 20, 0),
  ("musicos", "TUBAS", 21, 0),
  ("musicos", "HARMÔNICAS", 22, 0),
  ("localidades", "BANZAE", 1, 0),
  ("localidades", "IRMAS", 2, 0),
  ("localidades", "CAMANDAROBA", 3, 0),
  ("localidades", "ORGANISTA", 4, 0),
  ("localidades", "CANDIDATA", 5, 0),
  ("localidades", "CÍCERO DANTAS - CAMPINAS DE CASTRO", 6, 0),
  ("localidades", "CÍCERO DANTAS", 7, 0),
  ("localidades", "INTIUBA", 8, 0),
  ("localidades", "CÍCERO DANTAS - POVOADO SÃO JOÃO DA FORTALEZA", 9, 0),
  ("localidades", "CÍCERO DANTAS - POVOADO VILA SÃO PEDRO", 10, 0),
  ("localidades", "FILADELFIA", 11, 0),
  ("localidades", "HELIÓPOLIS", 12, 0),
  ("localidades", "HELIÓPOLIS - POVOADO TIJUCO", 13, 0),
  ("localidades", "JAGUARARI", 14, 0),
  ("localidades", "PARIPIRANGA", 15, 0),
  ("localidades", "PARIPIRANGA - FEIRINHA DO APERTADO DE PEDRAS", 16, 0),
  ("localidades", "RIBEIRA DO AMPARO - POVOADO RASPADOR", 17, 0),
  ("localidades", "RIBEIRA DO POMBAL", 18, 0),
  ("localidades", "RIBEIRA DO POMBAL - FAZENDA CANAVIEIRA", 19, 0),
  ("localidades", "RIBEIRA DO POMBAL - POMBALZINHO", 20, 0),
  ("localidades", "RIBEIRA DO POMBAL - POVOADO BOCA DA MATA", 21, 0),
  ("localidades", "RIBEIRA DO POMBAL - POVOADO NOVA ESPERANÇA", 22, 0),
  ("localidades", "COLONIA SERGIPE", 23, 0),
  ("localidades", "NOVA SOURE", 24, 0),
  ("localidades", "SALVADOR", 25, 0),
  ("localidades", "JINDIAROBA", 26, 0),
  ("localidades", "MALHADA NOVA", 27, 0),
  ("localidades", "JORRO", 28, 0),
  ("localidades", "OLINDINA", 29, 0),
  ("localidades", "POÇO VERDE", 30, 0),
  ("localidades", "MINAS", 31, 0),
  ("localidades", "BELO HORIZONTE", 32, 0),
  ("localidades", "ITAPICURU", 33, 0),
  ("localidades", "TUCANO", 34, 0),
  ("localidades", "PAULO AFONSO", 35, 0),
  ("localidades", "ARACAJU", 36, 0),
  ("localidades", "CRISOPOLIS", 37, 0),
  ("localidades", "KM 42", 38, 0),
  ("localidades", "CALOMBI", 39, 0),
  ("localidades", "SANTA BRIGIDA", 40, 0),
  ("localidades", "SP", 41, 0),
  ("localidades", "TOBIAS BARRETO", 42, 0),
  ("localidades", "FEIRA DE SANTANA", 43, 0),
  ("localidades", "CATU", 44, 0),
  ("localidades", "EUCLIDES DA CUNHA", 45, 0),
  ("localidades", "INHABUPE", 46, 0),
  ("localidades", "SERRINHA", 47, 0)
ON CONFLICT (grupo, nome) DO UPDATE
SET ordem = EXCLUDED.ordem;

INSERT INTO public.quantitativo_geral (chave, descricao, valor_texto, ordem)
VALUES
  ('ensaio_titulo','Título do ensaio','ENSAIO GERAL',1),
  ('ensaio_data','Data/local','',2),
  ('anciao','Ancião','',3),
  ('palavra','Palavra','',4),
  ('encarregados','Encarregados','',5),
  ('regencia','Regência','',6)
ON CONFLICT (chave) DO NOTHING;
